leek-wars/leek-wars

- http/lang/en/effect.lang
- http/lang/fr/effect.lang
- http/script/market.js
- http/style/market.css
Intégration de l'affichage des puces selon leurs effets.
Inspiré de l'user-script "Market Sort" de Jojo123 et Toufalk
> Market Sort integration

- http/script/garden.js
- Correction d'un bug qui ne faisait pas apparaître les ennemis
- Affichage de "Pas d'adversaire à ta taille !" quand c'est le cas
- Affichage de "Plus de combats" quand c'est le cas
> Correction des messages dans le potager

- http/lang/en/leek.lang
- http/lang/fr/leek.lang
- http/script/leek.js
- http/view/leek.html
- Utilisation des fichiers de langues pour les tooltips des caractéristiques
- Fix des messages d'erreurs d'équipement inversés.
> Traduction for characteristic tooltips

- http/script/editor.js
- http/script/report.js
- http/view/report.html
Ajoute la possibilité de relancer un combat de test avec les mêmes paramètres.
> Add the possibility of making a new test fight with same parameters

- http/script/market.js
> [market] Chip categories traduction

- http/lang/en/leek.lang
- http/lang/fr/leek.lang
- http/script/leek.js
- http/style/leek.css
- http/view/leek.html
Proposition pour cette issue : #27
> [leek] Add base life and added life in life tooltip

- http/script/_.js
- http/script/main.js
Wiki commands : 
/wiki
/wiki:page
/wiki:page#anchor
/wiki!
Doc commands: 
/doc
/doc:function
/doc!
Market commands : 
/market
/market:item
Other commands : 
/replacetable
/shrug
> [chat] Add helper commands and /replacetable

- http/style/garden.css
> [popup BR] Add border-radius style

- http/script/fight.js
> [fight] Exiting a fullscreen fight resize it to normal

- http/script/settings.js
Ça devrait éviter d'avoir des "ghost" sur le chat.
> [Settings] Disconnect and redirect user at the account's deletion

- http/lang/en/changelog.lang
Seeing this in the website was funny tbh
Mais oui.
> [lang] Removed the test changelog

- http/lang/en/fight.lang
Else it would have a weird sense i guess.
> [lang] Replaced clic by click

- http/lang/en/about.lang
- http/lang/en/editor.lang
- http/lang/en/login.lang
- http/lang/en/you_are_banned.lang
> Some fixes in spelling and language shit and stuffz

- http/script/garden.js
- http/style/garden.css
- http/view/garden.html
Affichage des erreurs d'IA non équipée ou invalide en solo.
l'Affichage est similaire à celui du "Pas d'adversaires à votre taille".
> [garden] No-ai and ai-invalid errors display

- http/script/main.js
> [Chat] Add a command : /lenny

- http/script/garden.js
#167 Set the countdown timer based on server time instead of local time
> [Garden] Fix the countdown timer

- http/lang/fr/forgot_password.lang
> [lang] Add missing line

- http/script/leek.js
Removes existing popups when loading the leek's page
> [Leek] Fix tooltypes disappearance

- CONTRIBUTING.md
Just fixing a little typing error line 25 :
- Create one pull request per feature OF bug fix you want to propose.
|
v
- Create one pull request per feature OR bug fix you want to propose.
> CONTRIBUTING.md : Fix typing error line 25 : "of" -> "or"

- http/script/main.js
> [logout] Correctly clear the token on disconnect

- http/script/main.js
- http/view/farmer.html
> [farmer] Remove message button when user is disconnected

- http/script/leek.js
#189 Ajout de la mise à jour de l'affichage du capital restant lorsque l'on quitte la popin des caractéristiques
> [Leek] Fix characteristics display

- http/script/forum_topic.js
> [topic] Fix anchor to a specific message

- http/script/leek.js
> [Leek] Fix bad variable name

- http/view/forum_topic.html
> [topic] Add anchor link to messages

- http/lang/en/farmer.lang
- http/lang/fr/farmer.lang
- http/script/farmer.js
J'ai mis une durée de 6 secondes sur l'affichage des erreurs pour laisser au user le temps de lire le message d'erreur
> [farmer] Display an error when tournament's registration failed

- http/script/main.js
This adds a few LaTeX common commands to the chat.
New commands are : \N, \Z, \Q, \R, \C, \iff, \implies, \inj, \surj and \qed.
> Latex macros

- http/script/main.js
Correction des boutons "Jouer !" et "Suivant" dans le didactitiel, en échangeant un show() et un hide().
> Rectification du "Jouer !" dans le didactitiel (Issue 149)

- http/script/game/game.js
I added a condition "&& game.sound" in the resume function.
Corresponds to the #220 issue.
> Disabling the atmosphere sound after a pause + unpause if game.sound is false

- http/lang/en/leek.lang
- http/lang/fr/leek.lang
Diverses corrections en français et en anglais de la page des poireaux, notamment syntaxiques.
> Page des poireaux : corrections du texte

- http/lang/en/general_help.lang
- http/lang/fr/general_help.lang
- http/lang/fr/tutorial.lang
- http/view/general_help.html
J'ai ajouté une description des BR dans l'aide (cela manquait) et ai retiré la partie à propos du pourcentage d'échecs des puces et des armes. J'ai aussi corrigé quelques fautes d'orthographe qui trainaient à quelques endroits et modifié quelques passages pouvant porter a confusion ou n'étant plus d'actualité.
> [Help] BR description and remove chips failure

- http/lang/en/main.lang
- http/lang/fr/main.lang
- http/script/chat_commands.js
- http/script/main.js
- http/script/messages.js
- http/style/chat.css
- http/view/chat.html
- http/view/forum.html
- http/view/head.html
- http/view/main.html
- http/view/messages.html
- http/view/team.html
#125 
http://imgur.com/a/2VM8y
> [Chat] Added popup list of chat commands

- http/script/main.js
> [Chat] Resolved sub-command auto-completion

- http/script/report.js
I managed to make a rather simple fix to #71 using the already available information. (Pretty nifty way of managing the effects by the way, nice work.)
This use two queues. One that is used at the beginning of a turn, as it is assumed all healing and damage will be iterated on before anything else in the leeks turn. As the leek gets its effects applied to him, each element is removed from the first queue and is put in the next turn's queue. Whenever a leek receive a new effect (poison or vaccine healing), the effect's id and the caster's id is put in the next turn's queue. Whenever an effect is removed, for each leek, both queues are filtered. This doesn't make much sense for the current turn's queue as it should always be empty, but I'd rather be safe than sorry.
There might be another …
> [Report] Fixing the report's statistics regarding poisons and vaccine

- http/lang/en/fight.lang
- http/lang/fr/fight.lang
- http/script/game/game.js
- http/script/report.js
Instead of having nothing in fight, or an ugly error in report, I propose to show which leek has been resurrected after the use of the chip Resurrection.
Before:
After:
I also changed the report section to avoid having empty divs using unnecessary space, which was making line spacing uneven.
> [Fight/Report] Action resurrection in fight and report

- http/script/game/game.js
- http/script/game/hud.js
- http/style/fight.css
- http/view/fight.html
Ajoute une petite tooltip au dessus de la barre de progression du fight pour savoir à quel tour on jumpera si on clique à cet endroit.
> Adds a tooltip on the fight progressbar to indicate the hovered turn

- http/lang/en/statistics.lang
- src/style/main.css
> Statistics page translation from French to English

- README.md
Modification of the licence date for legal reasons.
> Licence date

- src/script/chat_commands.js
- src/script/main.js
+ ajout d'une constante URL_TUTO
> Ajout de la commande /tuto, /tuto! et tri dans l'ordre alphabétique pour /ping

- src/script/chat_commands.js
il semblerait que je sois particulièrement mauvais pour faire un truc réussi du premier coup, mybad :(
> fix /tuto!

- src/component/chat/chat-input.vue
- src/lang/en/main.json
- src/lang/fr/main.json
Salut les poireaux,
Voici un petit fix pour une clé de traduction manquante.
> [chat] Fix "message too long" toast i18n

- src/lang/fr/documentation.json
Ce n'est pas super propre (3 commits au lieu d'1) car j'oubliais des virgules, mais sinon ca devrait etre bon. Avec cette modification, les utilisateurs auront l'info directement dans leekwars plutot que de devoir aller sur le wiki.
> Ajout de la documentation francaise pour les constantes EFFECT_*

- src/component/report/report.vue
Pas pu ajouter le style dans le scopped car après le PostCSS une balise data-v-### est ajoutée au css et non présente dans le <span>
> [Report] #444 added padding on even labels

- src/component/general-help/general-help.fr.i18n
Updated french help on TP stat cost (30+5 instead of 30+10)
> help update TP stat cost

- src/component/trophies/trophies.en.i18n
- src/component/trophies/trophies.fr.i18n
- src/component/trophies/trophies.vue
#538 
J'ai ajouté le tri par rareté visuellement de la même manière que "Cacher trophées obtenus". A voir si on préfère choisir aussi le sens de tri ¯\\_(ツ)_/¯
> [trophies] Sort by rarity

- src/lang/doc.fr.lang
Updated the example for arrayFlatten(array, depth) to use the depth
> Update doc.fr.lang in response to issue #580

- src/component/editor/editor.vue
- src/component/general-help/general-help.en.i18n
- src/component/general-help/general-help.fr.i18n
- src/component/tutorial/tutorial.fr.i18n
- src/component/tutorial/tutorial.vue
- src/lang/en/shortcut.json
- src/lang/fr/shortcut.json
[Tutorial] Update
-temakisushi
> [Various] Update

- src/lang/doc.en.lang
- src/lang/doc.fr.lang
[doc] Fix USE_TOO_MANY_SUMMONS
Thanks to nytope
> [doc] Fix USE_TOO_MANY_SUMMONS

- src/component/signup/signup.vue
[signup] Fix team
-temakisushi
> [signup] Fix team

- src/component/leek/leek.en.i18n
- src/component/leek/leek.fr.i18n
- src/component/leek/leek.vue
> Traduire "Register deleted" et "Register saved"

- src/component/player/player.vue
Merci à knarr qui a rapporté ce problème : https://leekwars.com/forum/category-3/topic-10429
> Modifier raccourci mode nuit

- src/component/editor/editor-test.vue
Ajout d'un bouton afin de dupliquer les caractéristiques et les items d'un poireau de test existant
> [Editor Test] Duplicate test leek

- src/component/garden/garden.en.i18n
- src/component/garden/garden.fr.i18n
- src/component/garden/garden.vue
"File d'attente" n'était pas traduit.
> [garden] translate queue

- src/component/report/report-block.vue
J'avais déjà corrigé ça pour le mode équipe dans #648
> Ne pas afficher le talent en test en éleveur

- src/component/leek/leek.vue
Corrige : https://leekwars.com/forum/category-3/topic-10715
> [pomp] nodge weapon tooltip on selection

- src/component/app/header.vue
Le clic sur l'icône des messages privés ne lit plus les notifications.
Corrige https://leekwars.com/forum/category-3/topic-10529
> [header] Click on messages must not clear notifs

- src/component/title/title.vue
Pour écrire l'adjectif "HL" en majuscules. Corrige http://localhost:8080/forum/category-4/topic-10740
> [title] Do not lowercase words with only uppercase

- src/component/farmer/farmer.en.i18n
- src/component/farmer/farmer.fr.i18n
- src/component/farmer/farmer.vue
Fix some translations on farmer page :)
> [farmer] Fix translations

- src/component/forum/forum-search.vue
> Fix bug #703

- src/lang/doc.fr.lang
> Fix typo for canUseChipOnCell doc

- src/component/forum/forum-category.vue
- src/component/forum/forum-topic.vue
> Manages deleted farmers in forum

- src/component/editor/editor-explorer.vue
Fix : https://leekwars.com/forum/category-3/topic-10022
I modified the original regex, so it takes the whole line, then I can check if there's // or /* *\ (if it's commented). If it is, we ignore it (don't include it in the downloaded file).
I also tested in localhost, and it's working
> [editor] Fix download includes

- src/component/editor/editor-explorer.vue
Fixes bug introduced by https://github.com/leek-wars/leek-wars/pull/715
> [editor] Fix optional semicolon for ai download with includes

- src/component/editor/editor-test.vue
There is no check done on the name, but currently we can submit anything in the "json encoded" leek, so I guess this is not a big deal ?
> [editor test] Update test leek name

- src/component/trophies/trophies.vue
Bonsoir, j'ai rajouté une toute petite fonctionnalité permettant de replier individuellement les catégories de trophées lorsque celles-ci sont activées.
> [feature] trophy categories foldable (RG88000)

- src/component/editor/editor-test.vue
#591 
J'ai mis une taille fixe à la prévisualisation de la map. Je n'ai pas mis les spawn des équipes
> Ajout preview Map de test

- src/component/farmer/farmer.vue
bugfix; css color was overriding darkmode in country selection
> bugfix dark mode for country selection

- src/component/forge/forge.vue
https://leekwars.com/forum/category-3/topic-11526
> fix bug with image of b-laser not found
