leek-wars/leek-wars

- DockerFile
Support pour Docker
**En production :** 
```
docker build -t leek-wars-client .
docker run --rm -p 8012:8012 -P leek-wars-client
+ reverse proxy vers le port 8012
ou http://ip:8012/
```
Attention: Ne print pas de logs
**En dev :**
```
docker build -t leek-wars-client .
docker run --rm -p 8012:8012 -v /path/to/local/app/folder:/app -it -P leek-wars-client /bin/sh
+ http://localhost:8012/
```
Applique les changements en live dans le container
Print les logs du script python
Attention: Il écoute sur 0.0.0.0 et pas en local par défaut
Testé sous **Windows 10 Pro** avec **Docker for windows**
> [docker] Docker support

- http/script/main.js
- http/style/chat.css
- http/style/main.css
- http/view/chat.html
- http/view/forum.html
- http/view/main.html
- Indiquer si il y a des nouveaux messages dans un bandeau;
- Bien garder le défilement automatique si l'utilisateur n'a pas scrollé vers le haut.
> Amélioration du scroll dans les chats (#5)

- http/script/game/game.js
Les appels à removeEffects vont déduire des caractéristiques initiales des poireaux les buffs qui se trouvent dans effects, d'où les effets négatifs qui s'affichent. 
Il suffit à la place de réinitialiser le tableau effects.
> Fix reset of effects, TP/inversion for timeline jump

- http/script/editor.js
Add the possibility to click on a AI list's blank space which allow
the selection of the root folder.
addClass('selected') is not required but it could be used to show that the root is selected.
resolves: #161
> [Editor] Fix creation of AI/folder on AI list's root

- http/script/report.js
La regex qui enlevait les espaces ne prenait pas en compte les espaces insécables des séparateurs des milliers, ce qui causait la mise en évidence de mauvaises valeurs
> [Report] Fix the highlight statistics table's bug

- http/script/main.js
Set time format to hh:mm:ss
e.g. print "05h 01m 18s" instead of "5h 1m 18s"
> [Garden] Change the countdown timer format

- http/lang/en/leek.lang
- http/lang/fr/leek.lang
- http/script/leek.js
- http/script/main.js
- http/script/market.js
- http/style/leek.css
- http/view/leek.html
Ajout d'erreurs "error_weapon_already_equipped" et "error_chip_already_equipped"
Il est désormais impossible d'équiper deux fois une même puce.
AJout d'une fonction orderChips dans LW.
Elle permet d'obtenir un objet associant un id de puce à un numéro de position.
Les positions correspondent aux puces ordonnées par type et pas niveau.
LW.orderedChips contient le retour de orderChips pour toutes les puces
Sur la page d'un poireau, et dans la popup d'équipement, les puces sont affichées dans l'ordre définit par LW.orderedChips
Dans la partie de la popup qui affiche les puces de l'éleveur, celles-ci sont regroupés en une seule.
La quantité est indiqué de la même façon que sur le Marché.
Modifications similaires pour les armes.
Suppression d'un ancien objet harcoder pour les langues
> [Leek] Improve equipment ui

- http/lang/en/hat.lang
- http/lang/fr/hat.lang
Certaines occurrences de "Noël" et "Christmas" étaient en minuscules ("noël" et "christmas") et d'autres non.
PR plus que secondaire, mais ça me gênait 😁.
> Majuscules à Noël et Christmas

- http/script/leek.js
- http/style/leek.css
- http/view/leek.html
Les chapeaux se stackent : 
Et plus de soucis de chapeaux qui ne réapparaissent pas dans la popup après l'avoir déséquipé, par exemple.
Et un fix sur les tableaux qui permettent de regrouper les armes/puces/chapeaux. Par un jeu de références, l'attribut quantity se retrouvait appliqué sur LW.farmer.weapons/chips/hats
> [Leek] Hat equipment

- src/script/game/game.js
When Liberation is used on an entity, only the hud is updated, so when the effect expire, the old value is used in `removeEffect` resulting in incorrect update of the stats displayed. This fix simply update the value contained in `this.effects[id].value`.
> [Fight] Fix incorrect display of stats when liberated effect expire

- src/component/report/report.vue
The chart showing the evolution of hp was showing 1hp for dead leeks instead of 0 in it's non-logarithmic version.
> change the life of leeks in the reports to 0hp when they are dead

- src/component/trophies/trophies.vue
Hi,
This commit fixes an overflow I encountered on trophies completion progression bar.
Before:
After:
I removed the width to allow flex containers resize. I validated this on
- Mozilla Firefox 80.0.1
- Chromium 85.0.4183.83
> Fix trophies stats bar overflow

- src/component/forum/breadcrumb.vue
Hi,
On firefox I noticed a veritcal disalignement on forum breadcrumb. This commit tries to fix it by removing an unecessary flex baseline alignment property. It works fine with and without on Chromium.
Before:
After:
> Fix forum breadcrumb vertical alignment

- src/component/farmer/farmer.vue
Replaces bad json serialization "[object Object]" to proper message
"team_already_used" or "Nom d'équipe déjà utilisé".
edit: I found some other places where this occurs (e.g. ban owner of team reject message)
> Fix toast message on team creation error

- src/component/history/history.vue
The team fight history was empty when, on an other history, the "Team" checkbox was not checked.
To reproduce the bug:
- Go to a leek or farmer history (example: https://leekwars.com/farmer/48992/history)
- Uncheck "Team"
- Go to a team history (example: https://leekwars.com/team/6132/history)
- The history is empty
Forum topic : https://leekwars.com/forum/category-3/topic-10322
> [Fix] Empty team fight history

- src/component/trophy/trophy.vue
Retire le texte "Pas encore débloqué" lorsqu'on a obtenu le trophée hors combat.
Corrige #634
> Retire le texte "Pas encore débloqué" lorsqu'on a obtenu le trophée hors combat.

- src/component/report/report-block.vue
Dans les combats d'éleveur et les combats d'équipe de test, le gain de talent (+/- NaN) était affiché. Déclaré dans https://leekwars.com/forum/category-3/topic-10444
> Ne pas afficher le talent en test

- src/component/report/statistics.ts
Dans les rapport de combat, l'équipe bleue est celle qui commence le combat. Or, dans les statistiques, les bleus sont ceux qui
ont gagné et les rouges les perdants. J'ai modifié ça sauf dans le cas d'une BR car c'est le seul type de combat où il y a plus de 2 équipes. (J'ai pensé à compter le nombre d'équipes pour avoir un code plus général, mais je n'ai pas trouvé de façon simple de le faire ; on pourrait itérer sur tous les poireaux et récupérer leur équipe.)
Déclaré ici : https://leekwars.com/forum/category-3/topic-10441
> Utiliser la même équipe dans les statistiques du rapport

- src/component/editor/ai-view.vue
- src/component/editor/editor.vue
- src/lang/en/shortcut.json
- src/lang/fr/shortcut.json
Adding 3 shortcuts to the editor view, with theirs translation in the UI (FR and EN).
Ctrl+Y → Fold all code blocks.
Ctrl+U → Toggle folding current code block.
Ctrl+I → Unfold all code blocks.
Tested locally on Firefox 91.8 ESR before submitting.
Note: Deleting a fork on a not merged PR is automatically closing it.
So, reissue of https://github.com/leek-wars/leek-wars/pull/651.
> [editor] Adding shortcuts to fold/unfold code blocks

- src/component/editor/editor-test.vue
Using "delete" inside test leek stat inputs no longer triggers the "delete IA" popup. It will still show up if you are not in a text box though.
We might want to completely disable the shortcuts of the page under the test editor (such as ALT+arrow_left/right).
> Fix issue #588 for test leek characteristics

- src/component/title/title.vue
Avec l'API on peut mettre un titre qui a un adjectif et pas de nom, et je pense qu'il n'y a pas de raison de bloquer cette possibilité.
- Affiche l'adjectif avec une majuscule s'il n'y a pas de nom
- Met une marge entre l'icône et l'adjectif s'il n'y a pas de nom
Corrige les points 1 et 2 de ce topic : https://leekwars.com/forum/category-3/topic-10723
> [title] Fix display with only adjective

- src/component/report/statistics.ts
Avant, si une attaque d'AOE touchait un ennemi et soi-même, les dégâts sur soi étaient comptés comme renvoi de dégâts chez l'ennemi : https://leekwars.com/forum/category-3/topic-10337
J'ai testé sur le combat 38619022.
Concernant les modifs, j'ai constaté que dans le cas ActionType.LIFE_LOST, il n'y a jamais de renvoi de dégâts, c'est géré dans le cas ActionType.DAMAGE_RETURN. Je ne suis pas 100% qu'il n'y ait pas de régressions en dehors de mon cas de test, c'est un peu compliqué les statistiques des combats ! A mon avis dans le cas LIFE_LOST on ne devrait pas à la fois toujours avoir entity.direct_dmg_in += damage et une condition sur les dégâts de poison, mais je crois qu'on n'entre pas dans LIFE_LOST sur des dégâts de poison.
> [statistics] Fix damage return on self AOE damage

- src/component/documentation/documentation.vue
Je ne sais pas dans quels cas "'item' in ..." est utile mais je doute que ce soit pour les popups car ça ne fonctionnait pas bien dans le marché.
Corrige les deux points du topic https://leekwars.com/forum/category-3/topic-10475
> [documentation] Rechercher depuis le marché

- src/component/trophies/trophies.en.i18n
In english, the word "défaut" is not translated on the trophies page. This fixes it :)
> Fix english translation for trophies default sorting

- src/lang/fr/potion.json
In french, the white and black potion is supposed to be "Potion blanche et noire" (the last e was missing).
> Fix white and black potion name in french

- src/component/editor/editor-test.vue
- src/component/garden/garden.vue
Avant, quand on entrait une seed puis qu'on mettait un espace, à cause de l'input de type "number", ça mettait "" (empty string) dans la seed. Si on met un input texte à la place, ce comportement disparaît et le parseInt se charge de supprimer le texte en trop. Par contre, si on met une lettre dans une seed vide ça afficherait "NaN" dans l'input, d'où la condition rajoutée dans updateSeed.
> [seed] seed + space = seed

- src/component/farmer/farmer.vue
When some has changed its username, the referral link should still refer to his first username, not the new one. This pull request change the referral link construction to use `farmer.login` instead of `farmer.name`.
For example, my referral link should be leekwars.com/godfather/T2006 instead of leekwars.com/godfather/bwbl (which is my current username in case you want to give me the contributor badge :wink:)
> Fix the referral link whenever user has changed its nickname

- src/component/report/report.en.i18n
- src/component/report/report.fr.i18n
- src/component/report/report.vue
When a report has only one error, it wrote "1 errors".
I did not test the change and did not change other languages.
> fix: Translation of n_errors in report

- src/component/editor/ai-view.vue
- src/component/editor/editor-finder.vue
I would sometimes delete files that I didn't mean to while using the search bar and pressing the "SUPPR/DELETE" key on my keyboard. Adding these keyup.stop seem to do the trick, but I'm not 100% sure that it is the way to go. (I could also check in the keyup function that we're not currently typing in a input tag).
> [editor] Fix unwanted deletion when pressing SUPPR in other inputs

- src/component/farmer/farmer.vue
When changing GitHub URL :
- `github.com/username` → `username`
- `https://github.com/username/` → `username/`
- `www.github.com/username` → `username`
- `username` → `username`
It avoids having ugly GitHub urls like : 
So the user can either copy and paste his GitHub profile link (or a repository), or he can just enter his username.
> [feature] GitHub URL regexp username

- src/component/editor/editor-explorer.vue
Some people complained ([here](https://leekwars.com/forum/category-3/topic-11040)) about having missing lines in their files. I suspected it had to do with the PR here https://github.com/leek-wars/leek-wars/commit/87c1f59d492cc634f5b5adad29171ebfb913d259 where the regexp was changed.
And indeed it was. It looks like the current regexp matches too many lines because of the "\s" when we don't use the ";" as a separator, the regexp matches the line below, and we delete all of the regexp match (even the extra line) to replace it with the included content.
Bonus point, it could also break functions which had "include" in the name. (example given below)
How to reproduce the bug : 
```
// File : main.leek
include('test.leek');
include('duplicated.leek')
// This line will disappear upon …
```
> [editor] Fix missing lines when exporting code

- src/component/inventory/inventory.vue
Avec template en clé il y avait des clés en double. Des erreurs l'indiquait dans la console, et ça causait un plantage de toute Vue.js. Cette modification corrige le plantage quand on passait du filtre Tout à Chapeaux : https://leekwars.com/forum/category-3/topic-10445
J'avais déjà corrigé ça dans le commit 422a0a6e2 mais Pilow l'a re-cassé !
> fix: Tri chapeaux
